# Generated by Django 2.0.1 on 2018-02-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180221_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='digraph',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digraph',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taskedge',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tasknode',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
